#!/bin/sh

# daily-mirror
# ============

# spiegelt einmal pro Tag bestimmte WWW-Seiten auf meinen lokalen Server

# Copyright (C) 2000 by Dirk Krummacker

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.   

# Datum       Autor             Änderungen
# -------------------------------------------------------------------------
# 31.03.2000  Dirk Krummacker   aus "ip-hangup-master" neu erzeugt
#

# in das Internet einwählen
/usr/local/bin/dial 2>&1 >/dev/null

# Nightlife updaten
rm /usr/local/apache/htdocs/mirror/nightlife/*
wget -P /usr/local/apache/htdocs/mirror/nightlife \
http://www.hamburg-cityguide.de/night.html

# aus dem Internet ausloggen
/usr/local/bin/hangup 2>&1 >/dev/null
