#!/bin/sh

# .ip-up
# ======

# Copyright (C) 2000 by Dirk Krummacker

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.   
 
# Autor             Datum        Änderungen
# --------------------------------------------------------------------
# Dirk Krummacker   11.03.2000   HERE-Documents eingebaut
# Dirk Krummacker   22.01.2000   Programmierung begonnen

# Einsammeln der Mails per fetchmail
fetchmail -a -s -vvv 2>&1

# Dynamische Adresse ermitteln und auf den Webserver bringen
# Basiert auf Message-ID: <38897fc1.1858882972@golden-gate.bie>
# von Uwe Bredemeier <uwe@call-n-deal.com>

cat >~/tmp/tmp.html <<EOF
<head>
  <meta http-equiv="expires" content="0">
  <meta http-equiv="refresh" content="0; URL=http://
EOF

# Adresse ermitteln
/sbin/ifconfig ippp0 | awk '/inet addr/{print substr($2,index($2,":")+1)}'\
        >>~/tmp/tmp.html

cat >>~/tmp/tmp.html <<EOF
">
  </head>
<body bgcolor="#FFFFFF">
<H2>
<center>
<b> Just a moment, you are being redirected to my local web server... </b>
</center>
</body>
EOF

# Linefeeds entfernen
delf ~/tmp/tmp.html ~/tmp/online.html

# alte .netrc sichern
if test -e ~/.netrc ; then
    mv ~/.netrc ~/.netrc.bak
fi

# Pseudo-.netrc schreiben
cat >>~/.netrc <<EOF
machine www.krummacker.de
login dac1690726
password TcsSmcuSA

macdef init
lcd /home/dirk/tmp
put online.html
close
quit

EOF

# sichere Rechte setzen
chmod 600 ~/.netrc

# Offline-Dokument auf Server bringen
ftp -d -v www.krummacker.de 2>&1

# alte .netrc wieder restaurieren
rm ~/.netrc
if test -e ~/.netrc.bak ; then
    mv ~/.netrc.bak ~/.netrc
fi

# Dateileichen entfernen
rm ~/tmp/tmp.html
rm ~/tmp/online.html

