#!/bin/bash
#
# =============================================================================
# small-backup
# =============================================================================
#
# Creates a backup of all important files in the system.
#

# the directory where to put tar archives in
ARCHIVE_DIR=/var/backup/small

# number of days to keep old backup files
LOCAL_PRESERVE_TIME=28

echo "starting small backup"

NOW=$(date +"%Y%m%d-%H%M")
ARCHIVE_LOCATION=$ARCHIVE_DIR/small-$NOW.tar.gz

# tar the stuff all at once
tar cvzf $ARCHIVE_LOCATION -T /etc/backup/small.includes \
    -X /etc/backup/small.excludes

echo "deleting local backups that are older than $LOCAL_PRESERVE_TIME days"
find $ARCHIVE_DIR -mtime +$LOCAL_PRESERVE_TIME -exec rm {} \;

# offer to encrypt and then burn a cd
echo -n "Do you want to burn the created backup archive to a CD-R (y/N)? "
read ANSWER
if [ "$ANSWER" = "y" ] ;
then
    TMP_DIR=/tmp/small-backup-burn.$NOW
    mkdir $TMP_DIR
    gpg --output $TMP_DIR/$(basename $ARCHIVE_LOCATION).gpg \
        -c $ARCHIVE_LOCATION
    echo -n "Please insert a CD-R and press <ENTER> to continue."
    read
    mkisofs -R -J $TMP_DIR | cdrecord -eject -v dev=/dev/hdd -
    rm -rf $TMP_DIR
else
    echo "Okay, next time perhaps ;-)"
fi
